### ISSUE TITLE
Windows zip has a trojan.

### ISSUE THREAD

**Issue by webprofusion-chrisc** [frectonz/sqlite-studio#5]
![image](https://github.com/frectonz/sqlite-studio/assets/2445502/cc09b231-d962-4b1d-9896-b90b9cbf4bc6)

**Comment by frectonz** [comment]
What!?

Can anybody else confirm this? I am on linux. I have not tested the windows build.

**Comment by 4silvertooth** [comment]
I confirm this.
![Screenshot 2024-06-17 104211](https://github.com/frectonz/sqlite-studio/assets/793967/a9fefdc7-75d2-4e9e-8258-9ea26f4b9b17)

**Comment by frectonz** [comment]
Ok i wasn't aware of this, will investigate further.

**Comment by webprofusion-chrisc** [comment]
It will most likely be a false positive caused by one of your dependencies being used in an established trojan so part of your resulting executable matches the same thumbprint, but I've no idea what. Alternatively one of your dependencies could genuinely be a trojan.

**Comment by 4silvertooth** [comment]
I built it it from source and it worked without any antivirus warnings.

**Comment by frectonz** [comment]
> Alternatively one of your dependencies could genuinely be a trojan.

Yeah thats what i'm worried about.

**Comment by ArneBachmannDLR** [comment]
Same for me - I assume a false positive, but that's definitely not going to be installed in a company context.
![grafik](https://github.com/frectonz/sqlite-studio/assets/54819781/ec3bd0f5-71af-4724-af5b-a34507779c6c)

**Comment by agamm** [comment]
Looking bad on virustotal:
https://www.virustotal.com/gui/file/7f03068475d962d7868e5da76712b593368f231d325debda061361a5c829d7b6/behavior

**Comment by drllz** [comment]
> Looking bad on virustotal: https://www.virustotal.com/gui/file/7f03068475d962d7868e5da76712b593368f231d325debda061361a5c829d7b6/

6 out of 78 scanners... not definitive, but certainly suspicious.

**Comment by ilotoki0804** [comment]
![image](https://github.com/frectonz/sqlite-studio/assets/130233823/48c6876f-e891-4909-9808-4b8854765b9c)
I am experiencing the same issue. Edge is not allowing me to download the file.

**Comment by frectonz** [comment]
From the research i did this seems to be a false positive. Installation no longer requires downloading a zip. We instead have powershell script, yall should use that instead.

https://github.com/frectonz/sqlite-studio#install-prebuilt-binaries-via-powershell-script
