### ISSUE TITLE
Visual clipping for tables with 10+ million rows

### ISSUE THREAD

**Issue by charlie-collard** [frectonz/sqlite-studio#7]
Hi, thanks for the cool tool! I'm seeing clipping on the y axis of the "Rows per table" bar chart for a table with ~88 million rows.

<kbd>
<img src="https://github.com/frectonz/sqlite-studio/assets/11244353/825b38b1-302e-4a9d-9a99-94542b237ff7" />
</kbd>

**Comment by charlie-collard** [comment]
The database isn't sensitive at all so if you'd like me to send it over I'd be happy to (it's about 30GB), it might also be useful for testing lazy-loading the UI on other areas of the tool

**Comment by frectonz** [comment]
I was trying to fix this but seems like the chart library i'm using [recharts](https://recharts.org/) doesn't provide a good way to solve this issue. :(

**Comment by charlie-collard** [comment]
@frectonz I think the `tickFormatter` option can be used, just tested it and created a PR :)
